### ISSUE TITLE
when I groupOTU  my tree some clades are Broken

### ISSUE THREAD

**Issue by xiaofeiyangyang** [GuangchuangYu/ggtree#24] opened 2015-10-30 02:55 UTC
Hi,yu
 my trouble is when I groupout my tree some clades are broken like this,I don't know how to deal with this trouble!as follow
![snapshot3](https://cloud.githubusercontent.com/assets/10369795/10837361/a4cad34a-7ef3-11e5-971a-c6082bd16361.png)
code is
ggtree(tree, aes(color=group),branch.length="none", layout = "circular", size = 0.5)

But if I cant't groupOUT the tree it's normal,view tree as follow
![snapshot4](https://cloud.githubusercontent.com/assets/10369795/10837437/60c5cfaa-7ef4-11e5-9d23-8a8f21290469.png)

code is 
ggtree(tree, branch.length = "none", layout = "circular", size = 0.5)

Do you kown what's wrong with me?

**Comment by GuangchuangYu** [comment] 2015-10-30 03:13
send me the tree pls. I will look into it.

**Comment by GuangchuangYu** [comment] 2015-10-30 05:30
the issue is due to `scale_color_manual(values=cols)`, but your `cols` is shorter than needed. So some lines don't have a color assign to them and then those lines will not visible.

In addition, you input `cols` is not consistent with the `group` feature, this is the reason why clades are not colored properly.

This is not an issue of `ggtree`.

**Closed by GuangchuangYu** 2015-10-30 05:30 UTC

**Comment by xiaofeiyangyang** [comment] 2015-10-30 08:12
thank you very much! I know where I'm wrong, I will check my code to solve this problem. But in my email about the taxon names are can't align, How can I aligning the taxon names by "ggtree" ?  Or where my questions are?

**Comment by GuangchuangYu** [comment] 2015-11-03 01:27
use `hjust=0`.

![screenshot 2015-11-03 09 27 08](https://cloud.githubusercontent.com/assets/626539/10899175/1e5112d0-820d-11e5-9ccf-648d27ac2777.png)

**Comment by xiaofeiyangyang** [comment] 2015-11-03 06:05
thank you!
