### ISSUE TITLE
TimeTree with geoscale

### ISSUE THREAD

**Issue by baozg** [GuangchuangYu/ggtree#202] opened 2018-10-12 03:18 UTC
Would `ggtree` add geoscale in `theme_tree2()`  for time tree like `strap` plot did(it combine phylo and 

```
library(strap)
data(Dipnoi)
tree_l <- DatePhylo(Dipnoi$tree, Dipnoi$ages, method="equal", rlen=1)
geoscalePhylo(tree=tree_l, ages=Dipnoi$ages, boxes="Age", cex.tip=0.4)
```
![image](https://user-images.githubusercontent.com/20680150/46845952-3f347080-ce10-11e8-8ee7-a73518396266.png)

**Comment by GuangchuangYu** [comment] 2018-10-12 06:46
see <https://github.com/willgearty/deeptime>.

**Comment by AEgit** [comment] 2019-01-25 11:03
This is a duplicate of https://github.com/GuangchuangYu/ggtree/issues/117#issue-211327510

**Closed** 2019-01-25 21:17 UTC
