### ISSUE TITLE
geom_treescale() error

### ISSUE THREAD

**Issue by cooketho** [GuangchuangYu/ggtree#111] opened 2017-01-25 03:30 UTC
When I try the following code I get an error:

> library(ggtree)
> beast_file <- system.file("examples/MCC_FluA_H3.tree", package="ggtree")
> beast_tree <- read.beast(beast_file)
> ggtree(beast_tree) + geom_treescale()
Error: stat_tree_scale_line requires the following missing aesthetics: xend, yend

> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggtree_1.2.17 ggplot2_2.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9         XVector_0.10.0      magrittr_1.5       
 [4] BiocGenerics_0.16.1 zlibbioc_1.16.0     IRanges_2.4.8      
 [7] munsell_0.4.3       colorspace_1.3-2    EBImage_4.12.2     
[10] ape_4.0             lattice_0.20-34     jpeg_0.1-8         
[13] plyr_1.8.4          tools_3.2.3         parallel_3.2.3     
[16] grid_3.2.3          gtable_0.2.0        nlme_3.1-129       
[19] png_0.1-7           abind_1.4-5         lazyeval_0.2.0     
[22] assertthat_0.1      tibble_1.2          tidyr_0.6.1        
[25] fftwtools_0.9-7     S4Vectors_0.8.11    tiff_0.1-5         
[28] scales_0.4.1        Biostrings_2.38.4   locfit_1.5-9.1     
[31] stats4_3.2.3        jsonlite_1.2

**Comment by hdetering** [comment] 2017-02-11 11:25
Can confirm, got the same error when trying to plot the scale on a simple Newick tree. A minimal working example:
>library(ggtree)
>tr <- read.tree("simple.tree")
>ggtree(tr) + geom_treescale()
>Error: stat_tree_scale_line requires the following missing aesthetics: xend, yend`

The tree used here:
`(C1:293,(C2:189,(C3:83,C4:100):91):94):150;`

> sessionInfo()
R version 3.2.5 (2016-04-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.7 (Final)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggtree_1.2.17 ggplot2_2.2.1 dplyr_0.5.0  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9         XVector_0.10.0      magrittr_1.5       
 [4] BiocGenerics_0.16.1 zlibbioc_1.16.0     IRanges_2.4.8      
 [7] munsell_0.4.3       colorspace_1.3-2    ape_4.0            
[10] lattice_0.20-34     R6_2.2.0            plyr_1.8.4         
[13] tools_3.2.5         parallel_3.2.5      grid_3.2.5         
[16] gtable_0.2.0        nlme_3.1-131        DBI_0.5-1          
[19] abind_1.4-5         lazyeval_0.2.0      assertthat_0.1     
[22] tibble_1.2          tidyr_0.6.1         S4Vectors_0.8.11   
[25] tiff_0.1-5          scales_0.4.1        Biostrings_2.38.4  
[28] locfit_1.5-9.1      stats4_3.2.5        jsonlite_1.2

**Comment by hdetering** [comment] 2017-02-11 12:26
Taking into account that the ggtree version (1.2.17) having that problem is a bit older, I assume it probably won't be fixed. Since I am constrained to R 3.2.5 due to working in a cluster environment, upgrading the current BioConductor release is not an option.

However, this **workaround** worked for me so I'll leave it here for anyone in a similar situation:
```
remove.packages("ggtree")
library(devtools)
install_git("https://github.com/Bioconductor-mirror/ggtree.git", branch="release-3.3")
```

**Comment by cooketho** [comment] 2017-02-11 17:29
Another workaround (what I ended up doing) is to manually plot a scale bar for the tree as a line segment. For example, the following is a code snippet to add a scale bar of 0.5 substitutions per site:

ls <- data.frame(x1=0, x2=0.5, y1=0, y2=0)
geom_segment(data=ls, aes(x=x1, xend=x2, y=y1, yend=y2))

**Comment by hdetering** [comment] 2017-02-11 19:56
Thanks for sharing your solution @cooketho. All that `geom_treescale()` does by default is draw a line segment - this is a  direct way to get done. Nice!

**Comment by GuangchuangYu** [comment] 2017-02-12 11:57
If you use latest release version of ggtree, there will be no problem.

The issue is caused by your installation with out-dated version of ggtree with latest version of ggplot2.

Update ggtree via `install_bioc` is a good option in this case.

**Closed by GuangchuangYu** 2017-02-12 11:57 UTC
